"use client";

/** Auto-generated by docs/scripts/generate-showcase-preview.mjs — do not edit manually. */
import React from "react";
import { PreviewAccordion } from "@/components/preview/accordion";
import { PreviewActionRail } from "@/components/preview/action-rail";
import { PreviewActionSheet } from "@/components/preview/action-sheet";
import { PreviewAlert } from "@/components/preview/alert";
import { PreviewAlertDialogDemo } from "@/components/preview/alert-dialog";
import { PreviewAnimateDemo } from "@/components/preview/animate";
import { PreviewAnimatedHeaderScrollView } from "@/components/preview/animated-header-scrollview";
import { PreviewAnimatedInputBar } from "@/components/preview/animated-input-bar";
import { PreviewArcList } from "@/components/preview/arc-list";
import { PreviewAreaChartDefault } from "@/components/preview/area-chart";
import { PreviewAspectRatio } from "@/components/preview/aspect-ratio";
import { PreviewAutoComplete } from "@/components/preview/autocomplete";
import { PreviewAvatar } from "@/components/preview/avatar";
import { PreviewAvatarGroup } from "@/components/preview/avatar-group";
import { PreviewBadge } from "@/components/preview/badge";
import { PreviewBanner } from "@/components/preview/banner";
import { PreviewBarChartDefault } from "@/components/preview/bar-chart";
import { PreviewBarcodeBadge } from "@/components/preview/barcode-badge";
import { PreviewBookPage } from "@/components/preview/book-page";
import { PreviewBorderBeam } from "@/components/preview/border-beam";
import { PreviewBottomSheet } from "@/components/preview/bottom-sheet";
import { PreviewBreadcrumb } from "@/components/preview/breadcrumb";
import { PreviewButton } from "@/components/preview/button";
import { PreviewCalendar } from "@/components/preview/calendar";
import { PreviewCard } from "@/components/preview/card";
import { PreviewCarousel } from "@/components/preview/carousel";
import { PreviewCarousel3D } from "@/components/preview/carousel-3d";
import { PreviewCarouselCircular } from "@/components/preview/carousel-circular";
import { PreviewCarouselParallax } from "@/components/preview/carousel-parallax";
import { PreviewCarouselScale } from "@/components/preview/carousel-scale";
import { PreviewCarouselTilt } from "@/components/preview/carousel-tilt";
import { PreviewChartTooltipDefault } from "@/components/preview/chart-tooltip";
import { PreviewChatBubbleDemo } from "@/components/preview/chat-bubble";
import { PreviewCheckbox } from "@/components/preview/checkbox";
import { PreviewChip } from "@/components/preview/chip";
import { PreviewCollapsible } from "@/components/preview/collapsible";
import { PreviewComboboxDemo } from "@/components/preview/combobox";
import { PreviewCommandMenuDemo } from "@/components/preview/command-menu";
import { PreviewConnectionBannerDemo } from "@/components/preview/connection-banner";
import { PreviewContextMenu } from "@/components/preview/context-menu";
import { PreviewCoupon } from "@/components/preview/coupon";
import { PreviewCurvedBottomTabs } from "@/components/preview/curved-bottom-tabs";
import { PreviewDataTableDemo } from "@/components/preview/data-table";
import { PreviewDatePickerDemo } from "@/components/preview/date-picker";
import { PreviewDialogDemo } from "@/components/preview/dialog";
import { PreviewDirectionProviderDemo } from "@/components/preview/direction-provider";
import { PreviewDisclosureGroup } from "@/components/preview/disclosure-group";
import { PreviewDrawer } from "@/components/preview/drawer";
import { PreviewDropdownMenu } from "@/components/preview/dropdown-menu";
import { PreviewEmptyState } from "@/components/preview/empty-state";
import { PreviewEventTicket } from "@/components/preview/event-ticket";
import { PreviewExpandableView } from "@/components/preview/expandable-view";
import { PreviewFAB } from "@/components/preview/fab";
import { PreviewFanMenu } from "@/components/preview/fan-menu";
import { PreviewFieldDemo } from "@/components/preview/field";
import { PreviewFilePickerDemo } from "@/components/preview/file-picker";
import { PreviewFillingStack } from "@/components/preview/filling-stack";
import { PreviewFlexiButton } from "@/components/preview/flexi-button";
import { PreviewFlipCard } from "@/components/preview/flip-card";
import { PreviewFormDemo } from "@/components/preview/form";
import { PreviewGooeyPopover } from "@/components/preview/gooey-popover";
import { PreviewGooeySearchTabs } from "@/components/preview/gooey-search-tabs";
import { PreviewGooeySwitch } from "@/components/preview/gooey-switch";
import { PreviewGradient } from "@/components/preview/gradient";
import { PreviewGridDemo } from "@/components/preview/grid";
import { PreviewHamburger } from "@/components/preview/hamburger";
import { PreviewHeaderDemo } from "@/components/preview/header";
import { PreviewHoverCardDemo } from "@/components/preview/hover-card";
import { PreviewImage } from "@/components/preview/image";
import { PreviewImageGalleryDemo } from "@/components/preview/image-gallery";
import { PreviewInfiniteListDemo } from "@/components/preview/infinite-list";
import { PreviewInput } from "@/components/preview/input";
import { PreviewInputGroupDemo } from "@/components/preview/input-group";
import { PreviewInputOTP } from "@/components/preview/input-otp";
import { PreviewKbdDemo } from "@/components/preview/kbd";
import { PreviewKeyboardViewDemo } from "@/components/preview/keyboard-view";
import { PreviewLabel } from "@/components/preview/label";
import { PreviewLabeledSeparatorDemo } from "@/components/preview/labeled-separator";
import { PreviewLineChartDefault } from "@/components/preview/line-chart";
import { PreviewList } from "@/components/preview/list";
import { PreviewLoader } from "@/components/preview/loader";
import { PreviewMarquee } from "@/components/preview/marquee";
import { PreviewMaskedInputDemo } from "@/components/preview/masked-input";
import { PreviewMatchedGeometry } from "@/components/preview/matched-geometry";
import { PreviewMenubar } from "@/components/preview/menubar";
import { PreviewMobileDock } from "@/components/preview/mobile-dock";
import { PreviewMorphFab } from "@/components/preview/morph-fab";
import { PreviewMorphLoader } from "@/components/preview/morph-loader";
import { PreviewMorphingTabbar } from "@/components/preview/morphing-tabbar";
import { PreviewNumberInputDemo } from "@/components/preview/number-input";
import { PreviewPaginationDemo } from "@/components/preview/pagination";
import { PreviewPasswordInputDemo } from "@/components/preview/password-input";
import { PreviewPhoneInputDemo } from "@/components/preview/phone-input";
import { PreviewPhotoStack } from "@/components/preview/photo-stack";
import { PreviewPieChartDefault } from "@/components/preview/pie-chart";
import { PreviewPolaroid } from "@/components/preview/polaroid";
import { PreviewPopoverDemo } from "@/components/preview/popover";
import { PreviewPriceDemo } from "@/components/preview/price";
import { PreviewProfileCard } from "@/components/preview/profile-card";
import { PreviewProgress } from "@/components/preview/progress";
import { PreviewProgressStepsDemo } from "@/components/preview/progress-steps";
import { PreviewPromptInput } from "@/components/preview/prompt-input";
import { PreviewQrCode } from "@/components/preview/qr-code";
import { PreviewRadarChartDefault } from "@/components/preview/radar-chart";
import { PreviewRadialChartDefault } from "@/components/preview/radial-chart";
import { PreviewRadiantButton } from "@/components/preview/radiant-button";
import { PreviewRadioGroup } from "@/components/preview/radio-group";
import { PreviewRating } from "@/components/preview/rating";
import { PreviewReceiptCard } from "@/components/preview/receipt-card";
import { PreviewRefreshControlDemo } from "@/components/preview/refresh-control";
import { PreviewRollingCounter } from "@/components/preview/rolling-counter";
import { PreviewSafeAreaDemo } from "@/components/preview/safe-area";
import { PreviewSaveButton } from "@/components/preview/save-button";
import { PreviewSearchBar } from "@/components/preview/search-bar";
import { PreviewSegmentedControl } from "@/components/preview/segmented-control";
import { PreviewSelect } from "@/components/preview/select";
import { PreviewSeparator } from "@/components/preview/separator";
import { PreviewShimmer } from "@/components/preview/shimmer";
import { PreviewSidebar } from "@/components/preview/sidebar";
import { PreviewSkeleton } from "@/components/preview/skeleton";
import { PreviewSlideToConfirm } from "@/components/preview/slide-to-confirm";
import { PreviewSlider } from "@/components/preview/slider";
import { PreviewSocialButton } from "@/components/preview/social-button";
import { PreviewSpinButton } from "@/components/preview/spin-button";
import { PreviewSpinner } from "@/components/preview/spinner";
import { PreviewSplitView } from "@/components/preview/split-view";
import { PreviewSquircleView } from "@/components/preview/squircle-view";
import { PreviewStackedChips } from "@/components/preview/stacked-chips";
import { PreviewStatCardDemo } from "@/components/preview/stat-card";
import { PreviewStatusIndicatorDemo } from "@/components/preview/status-indicator";
import { PreviewStepper } from "@/components/preview/stepper";
import { PreviewStreamingText } from "@/components/preview/streaming-text";
import { PreviewSwipeDeckDemo } from "@/components/preview/swipe-deck";
import { PreviewSwipeableListItem } from "@/components/preview/swipeable-list-item";
import { PreviewSwitch } from "@/components/preview/switch";
import { PreviewTabBarDemo } from "@/components/preview/tab-bar";
import { PreviewTable } from "@/components/preview/table";
import { PreviewTabsDemo } from "@/components/preview/tabs";
import { PreviewText } from "@/components/preview/text";
import { PreviewTextarea } from "@/components/preview/textarea";
import { PreviewThemeProviderDemo } from "@/components/preview/theme-provider";
import { PreviewThemeSwitch } from "@/components/preview/theme-switch";
import { PreviewTimelineDemo } from "@/components/preview/timeline";
import { PreviewToastProvider } from "@/components/preview/toast";
import { PreviewToggle } from "@/components/preview/toggle";
import { PreviewToggleGroup } from "@/components/preview/toggle-group";
import { PreviewTooltip } from "@/components/preview/tooltip";
import { PreviewTray } from "@/components/preview/tray";
import { PreviewTypingIndicatorDemo } from "@/components/preview/typing-indicator";
import { PreviewUnfoldMenu } from "@/components/preview/unfold-menu";
import { PreviewVerifiedBadge } from "@/components/preview/verified-badge";
import { PreviewVerifiedShine } from "@/components/preview/verified-shine";
import { PreviewWaveform } from "@/components/preview/waveform";

const previewMap = {
  accordion: PreviewAccordion,
  "action-rail": PreviewActionRail,
  "action-sheet": PreviewActionSheet,
  alert: PreviewAlert,
  "alert-dialog": PreviewAlertDialogDemo,
  animate: PreviewAnimateDemo,
  "animated-header-scrollview": PreviewAnimatedHeaderScrollView,
  "animated-input-bar": PreviewAnimatedInputBar,
  "arc-list": PreviewArcList,
  "area-chart": PreviewAreaChartDefault,
  "aspect-ratio": PreviewAspectRatio,
  autocomplete: PreviewAutoComplete,
  avatar: PreviewAvatar,
  "avatar-group": PreviewAvatarGroup,
  badge: PreviewBadge,
  banner: PreviewBanner,
  "bar-chart": PreviewBarChartDefault,
  "barcode-badge": PreviewBarcodeBadge,
  "book-page": PreviewBookPage,
  "border-beam": PreviewBorderBeam,
  "bottom-sheet": PreviewBottomSheet,
  breadcrumb: PreviewBreadcrumb,
  button: PreviewButton,
  calendar: PreviewCalendar,
  card: PreviewCard,
  carousel: PreviewCarousel,
  "carousel-3d": PreviewCarousel3D,
  "carousel-circular": PreviewCarouselCircular,
  "carousel-parallax": PreviewCarouselParallax,
  "carousel-scale": PreviewCarouselScale,
  "carousel-tilt": PreviewCarouselTilt,
  "chart-tooltip": PreviewChartTooltipDefault,
  "chat-bubble": PreviewChatBubbleDemo,
  checkbox: PreviewCheckbox,
  chip: PreviewChip,
  collapsible: PreviewCollapsible,
  combobox: PreviewComboboxDemo,
  "command-menu": PreviewCommandMenuDemo,
  "connection-banner": PreviewConnectionBannerDemo,
  "context-menu": PreviewContextMenu,
  coupon: PreviewCoupon,
  "curved-bottom-tabs": PreviewCurvedBottomTabs,
  "data-table": PreviewDataTableDemo,
  "date-picker": PreviewDatePickerDemo,
  dialog: PreviewDialogDemo,
  "direction-provider": PreviewDirectionProviderDemo,
  "disclosure-group": PreviewDisclosureGroup,
  drawer: PreviewDrawer,
  "dropdown-menu": PreviewDropdownMenu,
  "empty-state": PreviewEmptyState,
  "event-ticket": PreviewEventTicket,
  "expandable-view": PreviewExpandableView,
  fab: PreviewFAB,
  "fan-menu": PreviewFanMenu,
  field: PreviewFieldDemo,
  "file-picker": PreviewFilePickerDemo,
  "filling-stack": PreviewFillingStack,
  "flexi-button": PreviewFlexiButton,
  "flip-card": PreviewFlipCard,
  form: PreviewFormDemo,
  "gooey-popover": PreviewGooeyPopover,
  "gooey-search-tabs": PreviewGooeySearchTabs,
  "gooey-switch": PreviewGooeySwitch,
  gradient: PreviewGradient,
  grid: PreviewGridDemo,
  hamburger: PreviewHamburger,
  header: PreviewHeaderDemo,
  "hover-card": PreviewHoverCardDemo,
  image: PreviewImage,
  "image-gallery": PreviewImageGalleryDemo,
  "infinite-list": PreviewInfiniteListDemo,
  input: PreviewInput,
  "input-group": PreviewInputGroupDemo,
  "input-otp": PreviewInputOTP,
  kbd: PreviewKbdDemo,
  "keyboard-view": PreviewKeyboardViewDemo,
  label: PreviewLabel,
  "labeled-separator": PreviewLabeledSeparatorDemo,
  "line-chart": PreviewLineChartDefault,
  list: PreviewList,
  loader: PreviewLoader,
  marquee: PreviewMarquee,
  "masked-input": PreviewMaskedInputDemo,
  "matched-geometry": PreviewMatchedGeometry,
  menubar: PreviewMenubar,
  "mobile-dock": PreviewMobileDock,
  "morph-fab": PreviewMorphFab,
  "morph-loader": PreviewMorphLoader,
  "morphing-tabbar": PreviewMorphingTabbar,
  "number-input": PreviewNumberInputDemo,
  pagination: PreviewPaginationDemo,
  "password-input": PreviewPasswordInputDemo,
  "phone-input": PreviewPhoneInputDemo,
  "photo-stack": PreviewPhotoStack,
  "pie-chart": PreviewPieChartDefault,
  polaroid: PreviewPolaroid,
  popover: PreviewPopoverDemo,
  price: PreviewPriceDemo,
  "profile-card": PreviewProfileCard,
  progress: PreviewProgress,
  "progress-steps": PreviewProgressStepsDemo,
  "prompt-input": PreviewPromptInput,
  "qr-code": PreviewQrCode,
  "radar-chart": PreviewRadarChartDefault,
  "radial-chart": PreviewRadialChartDefault,
  "radiant-button": PreviewRadiantButton,
  "radio-group": PreviewRadioGroup,
  rating: PreviewRating,
  "receipt-card": PreviewReceiptCard,
  "refresh-control": PreviewRefreshControlDemo,
  "rolling-counter": PreviewRollingCounter,
  "safe-area": PreviewSafeAreaDemo,
  "save-button": PreviewSaveButton,
  "search-bar": PreviewSearchBar,
  "segmented-control": PreviewSegmentedControl,
  select: PreviewSelect,
  separator: PreviewSeparator,
  shimmer: PreviewShimmer,
  sidebar: PreviewSidebar,
  skeleton: PreviewSkeleton,
  "slide-to-confirm": PreviewSlideToConfirm,
  slider: PreviewSlider,
  "social-button": PreviewSocialButton,
  "spin-button": PreviewSpinButton,
  spinner: PreviewSpinner,
  "split-view": PreviewSplitView,
  "squircle-view": PreviewSquircleView,
  "stacked-chips": PreviewStackedChips,
  "stat-card": PreviewStatCardDemo,
  "status-indicator": PreviewStatusIndicatorDemo,
  stepper: PreviewStepper,
  "streaming-text": PreviewStreamingText,
  "swipe-deck": PreviewSwipeDeckDemo,
  "swipeable-list-item": PreviewSwipeableListItem,
  switch: PreviewSwitch,
  "tab-bar": PreviewTabBarDemo,
  table: PreviewTable,
  tabs: PreviewTabsDemo,
  text: PreviewText,
  textarea: PreviewTextarea,
  "theme-provider": PreviewThemeProviderDemo,
  "theme-switch": PreviewThemeSwitch,
  timeline: PreviewTimelineDemo,
  toast: PreviewToastProvider,
  toggle: PreviewToggle,
  "toggle-group": PreviewToggleGroup,
  tooltip: PreviewTooltip,
  tray: PreviewTray,
  "typing-indicator": PreviewTypingIndicatorDemo,
  "unfold-menu": PreviewUnfoldMenu,
  "verified-badge": PreviewVerifiedBadge,
  "verified-shine": PreviewVerifiedShine,
  waveform: PreviewWaveform,
} as unknown as Record<string, React.ComponentType<{ className?: string }>>;

export function ShowcasePreview({ slug, className }: { slug: string; className?: string }) {
  const Preview = previewMap[slug];
  if (!Preview) {
    return (
      <div className={className}>
        <p className="text-xs text-muted-foreground text-center px-4">Preview unavailable</p>
      </div>
    );
  }
  return <Preview className={className} />;
}

export { previewMap };
