/* ── Shared navigation data — single source of truth ────────── */

export type NavItem = { title: string; href: string };
export type NavSection = { title: string; items: NavItem[] };

export const gettingStartedItems: NavItem[] = [
  { title: "Introduction", href: "/docs" },
  { title: "Installation", href: "/docs/installation" },
  { title: "JavaScript", href: "/docs/javascript" },
  { title: "CLI", href: "/docs/cli" },
  { title: "MCP", href: "/docs/mcp" },
  { title: "Theming", href: "/docs/theming" },
  { title: "Dark Mode", href: "/docs/dark-mode" },
  { title: "Theme Provider", href: "/docs/theme-provider" },
  { title: "Compatibility", href: "/docs/compatibility" },
  { title: "Android", href: "/docs/android" },
  { title: "Uniwind", href: "/docs/uniwind" },
  { title: "Changelog", href: "/docs/changelog" },
  { title: "Create", href: "/create" },
];

export const componentItems: NavItem[] = [
  { title: "Accordion", href: "/docs/accordion" },
  { title: "Action Sheet", href: "/docs/action-sheet" },
  { title: "Alert", href: "/docs/alert" },
  { title: "Alert Dialog", href: "/docs/alert-dialog" },
  { title: "Avatar", href: "/docs/avatar" },
  { title: "Badge", href: "/docs/badge" },
  { title: "Banner", href: "/docs/banner" },
  { title: "Bottom Sheet", href: "/docs/bottom-sheet" },
  { title: "Button", href: "/docs/button" },
  { title: "Calendar", href: "/docs/calendar" },
  { title: "Card", href: "/docs/card" },
  { title: "Carousel", href: "/docs/carousel" },
  { title: "Chat Bubble", href: "/docs/chat-bubble" },
  { title: "Checkbox", href: "/docs/checkbox" },
  { title: "Chip", href: "/docs/chip" },
  { title: "Collapsible", href: "/docs/collapsible" },
  { title: "Combobox", href: "/docs/combobox" },
  { title: "Connection Banner", href: "/docs/connection-banner" },
  { title: "Context Menu", href: "/docs/context-menu" },
  { title: "Date Picker", href: "/docs/date-picker" },
  { title: "Dialog", href: "/docs/dialog" },
  { title: "Drawer", href: "/docs/drawer" },
  { title: "Dropdown Menu", href: "/docs/dropdown-menu" },
  { title: "Empty State", href: "/docs/empty-state" },
  { title: "FAB", href: "/docs/fab" },
  { title: "File Picker", href: "/docs/file-picker" },
  { title: "Form", href: "/docs/form" },
  { title: "Grid", href: "/docs/grid" },
  { title: "Header", href: "/docs/header" },
  { title: "Image", href: "/docs/image" },
  { title: "Image Gallery", href: "/docs/image-gallery" },
  { title: "Infinite List", href: "/docs/infinite-list" },
  { title: "Input", href: "/docs/input" },
  { title: "Input OTP", href: "/docs/input-otp" },
  { title: "Label", href: "/docs/label" },
  { title: "Labeled Separator", href: "/docs/labeled-separator" },
  { title: "List", href: "/docs/list" },
  { title: "Masked Input", href: "/docs/masked-input" },
  { title: "Number Input", href: "/docs/number-input" },
  { title: "Pagination", href: "/docs/pagination" },
  { title: "Password Input", href: "/docs/password-input" },
  { title: "Phone Input", href: "/docs/phone-input" },
  { title: "Popover", href: "/docs/popover" },
  { title: "Price", href: "/docs/price" },
  { title: "Progress", href: "/docs/progress" },
  { title: "Progress Steps", href: "/docs/progress-steps" },
  { title: "Radio Group", href: "/docs/radio-group" },
  { title: "Rating", href: "/docs/rating" },
  { title: "Refresh Control", href: "/docs/refresh-control" },
  { title: "Safe Area", href: "/docs/safe-area" },
  { title: "Search Bar", href: "/docs/search-bar" },
  { title: "Segmented Control", href: "/docs/segmented-control" },
  { title: "Select", href: "/docs/select" },
  { title: "Separator", href: "/docs/separator" },
  { title: "Skeleton", href: "/docs/skeleton" },
  { title: "Slider", href: "/docs/slider" },
  { title: "Spinner", href: "/docs/spinner" },
  { title: "Stat Card", href: "/docs/stat-card" },
  { title: "Status Indicator", href: "/docs/status-indicator" },
  { title: "Stepper", href: "/docs/stepper" },
  { title: "Swipeable List Item", href: "/docs/swipeable-list-item" },
  { title: "Switch", href: "/docs/switch" },
  { title: "Tab Bar", href: "/docs/tab-bar" },
  { title: "Table", href: "/docs/table" },
  { title: "Tabs", href: "/docs/tabs" },
  { title: "Text", href: "/docs/text" },
  { title: "Textarea", href: "/docs/textarea" },
  { title: "Timeline", href: "/docs/timeline" },
  { title: "Toast", href: "/docs/toast" },
  { title: "Toggle", href: "/docs/toggle" },
  { title: "Toggle Group", href: "/docs/toggle-group" },
  { title: "Tooltip", href: "/docs/tooltip" },
  { title: "Typing Indicator", href: "/docs/typing-indicator" },
];

export const chartItems: NavItem[] = [
  { title: "Area Chart", href: "/charts/area-chart" },
  { title: "Bar Chart", href: "/charts/bar-chart" },
  { title: "Line Chart", href: "/charts/line-chart" },
  { title: "Pie Chart", href: "/charts/pie-chart" },
  { title: "Radar Chart", href: "/charts/radar-chart" },
  { title: "Radial Chart", href: "/charts/radial-chart" },
  { title: "Tooltip", href: "/charts/tooltip" },
];

export const blockItems: NavItem[] = [
  { title: "Login", href: "/blocks/login" },
  { title: "Sign Up", href: "/blocks/signup" },
  { title: "Forgot Password", href: "/blocks/forgot-password" },
  { title: "Home Screen", href: "/blocks/home" },
  { title: "Bottom Tabs", href: "/blocks/bottom-tabs" },
  { title: "Drawer Navigation", href: "/blocks/drawer-nav" },
  { title: "Profile", href: "/blocks/profile" },
  { title: "Settings", href: "/blocks/settings" },
  { title: "Onboarding", href: "/blocks/onboarding" },
  { title: "Chat", href: "/blocks/chat" },
  { title: "Product List", href: "/blocks/product-list" },
  { title: "Product Detail", href: "/blocks/product-detail" },
  { title: "Notifications", href: "/blocks/notifications" },
  { title: "Pricing", href: "/blocks/pricing" },
  { title: "Search", href: "/blocks/search" },
];

export const sidebarSections: NavSection[] = [
  { title: "Getting Started", items: gettingStartedItems },
  { title: "Components", items: componentItems },
  { title: "Charts", items: chartItems },
  { title: "Blocks", items: blockItems },
];
